FROM tedneward/openjdkbase
MAINTAINER Ted Neward (ted@tedneward.com)

# Grab the boot JDK
#RUN apt-get install -y openjdk-7-jdk

RUN add-apt-repository ppa:openjdk-r/ppa && \
    apt-get update && \
    apt-get install -y openjdk-7-jdk 
