version: "3"
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=casscluster
    ports: # Cassandra exposes 7000 7001 7199 9042 9160
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"

  usergrid:
    build: .
    #image: gaborwnuk/usergrid
    environment:
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_CLUSTER_NAME=casscluster
    links:
      - cassandra
    ports:
      - "8080:8080"
